# Generated by Django 4.0.7 on 2022-08-10 10:09

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, verbose_name='Budget'),
        ),
    ]
